### ISSUE TITLE
[Notarize the app for use simplicity on mac]

### ISSUE THREAD

**Issue by jadczakd** [Nishkalkashyap/Quark-electron#11]
### Problem Description
Mac is preventing the launch of the app because of a missing / self-signed cert. It will be causing issues with updates, and is right now with starting the app up initially.

### Proposed Solution
Read + implement https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

### Alternatives Considered
Not aware of alternatives for now.

### Additional Information
<img width="428" alt="Screenshot 2019-08-19 at 11 41 43" src="https://user-images.githubusercontent.com/20739064/63255631-5769ed00-c276-11e9-8407-92670e4c4b38.png">

**Comment by Nishkalkashyap** [comment]
Hey @jadczakd . Thanks for opening your first issue here. I can confirm this is a bug. 

The notarization step was already implemented. But for some reason it did not throw an error when notarization failed in the previous build. I'm working to fix the issue ASAP.

**Comment by jadczakd** [comment]
@Nishkalkashyap No worries - sorry I can't be of more help for now - also the app works great, I am just worried you can miss on some less technical audience due to this inconvenience. You can still start it up if you know about security / run it as root account and all.
Great work!

**Comment by Nishkalkashyap** [comment]
@jadczakd  Again. Thanks for informing! 

I've already published a new version in the insiders-release-channel. You can download it from [here](https://quarkjs.io/download/insiders.html). 

If you find that the issue has been resolved, feel free to close this issue. Cheers!

**Comment by jadczakd** [comment]
Works great now :) Thanks for the swift action :)
