### ISSUE TITLE
Quark-win-0.5.6  install Trouble

### ISSUE THREAD

**Issue by megadox** [Nishkalkashyap/Quark-electron#5]
Quark-win-0.5.6 Version is not installed (all of exe / msi /zip)

![err](https://user-images.githubusercontent.com/1289924/62027194-07b87880-b218-11e9-86ff-189b2c57892b.png)

**Comment by Nishkalkashyap** [comment]
Hey @megadox . Thanks for opening your first issue. 

I could not confirm the error here. The installer is working fine on current version of windows, as well as windows 7. Could you share some more details like windows version etc.?

**Comment by megadox** [comment]
My PC OS is Windows 7 Professional - 64bit, and the .Net Framework is 4.7.2. 
And nsis's product Nullsoft Install System (NSIS - Version 3.04) is installed.

**Comment by k19812** [comment]
Same Trouble.
Windows 10 Pro.

**Comment by Nishkalkashyap** [comment]
Ok. I thought it was a problem with windows 7 going out of support or something. If this is happening with windows 10, I might need to take a fresh look.

Meanwhile, could you try the [insiders release](https://quarkjs.io/download/insiders.html) and let me know if that throws the same error.? 

@k19812  @megadox

**Comment by k19812** [comment]
@Nishkalkashyap 

It worked for me!
Quark is beautiful IDE.
It's the tool I wanted. (NW.js -> Electron -> Quark)
Thank you.

![quark](https://user-images.githubusercontent.com/3230239/62639637-e6276180-b97a-11e9-9a33-c28133b1b015.PNG)

**Comment by Nishkalkashyap** [comment]
Closing this issue. I believe it was a bad release that caused the bug. If you see otherwise, feel free to open a new issue.
